.ubuntu:template: &ubuntu_template
  image: ubuntu:bionic
  script:
    - bash ubuntu.$config.sh -d bionic -l us -u $(whoami)
    - bash ubuntu.$config.test.sh

ubuntu:base:
  variables:
    config: base
  <<: *ubuntu_template
  only:
    changes:
      - ubuntu.base.sh
      - ubuntu.base.test.sh

ubuntu:desktop:
  variables:
    config: desktop
  <<: *ubuntu_template
  only:
    changes:
      - ubuntu.base.sh
      - ubuntu.base.test.sh
      - ubuntu.desktop.sh
      - ubuntu.desktop.test.sh
      - conda/*.yml
