dist: xenial
language: python
sudo: required
services:
  - docker
env:
  - config=base
  - config=desktop

jobs:
  include:
    - script:
        - sudo docker run -v $PWD:/build ubuntu:bionic /bin/bash -c "cd /build; bash ci/ubuntu.sh $config"
