[automount]
enabled = true
root = /mnt/
options = "metadata,fmask=0133,dmask=0022"
mountFsTab = true

[network]
generateHosts = true
generateResolvConf = true

[interop]
enabled = true
appendWindowsPath = true
