name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8
  - babel
  - beautifulsoup4
  - bokeh
  - cffi
  - conda
  - conda-env
  - conda-verify
  - cython
  - cytoolz
  - dask
  - flask
  - flask-cors
  - future
  - gensim
  - ipykernel
  - ipyparallel
  - ipython
  - ipywidgets
  - jcc
  - jpeg
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - markdown
  - matplotlib
  - more-itertools
  - multipledispatch
  - mypy
  - nb_conda
  - networkx
  - nltk
  - notebook
  - numba
  - numexpr
  - numpy
  - pandas
  - pandoc
  - pathlib2
  - pcre
  - pefile
  - pep8
  - pep8-naming
  - pillow
  - pip
  - psutil
  - pycodestyle
  - pycurl
  - pylint
  - python
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - scrapy
  - seaborn
  - selenium
  - simplegeneric
  - singledispatch
  - snappy
  - sortedcollections
  - spacy
  - statsmodels
  - sympy
  - toolz
  - typing
  - whoosh
  - widgetsnbextension
  - wxpython
  - pip:
    - docker-compose
    - python-openstackclient
