jobs:
  - job: ubuntu
    pool:
      vmImage: "ubuntu-16.04"
    strategy:
      parallel: 2
      matrix:
        base:
          config: base
        desktop:
          config: desktop
    container: ubuntu:bionic
    steps:
      - script: bash ubuntu.$[variables['config']].sh -d bionic -l us -u $(whoami)
      - script: bash ubuntu.$[variables['config']].test.sh
