jobs:
  - job: Ubuntu
    pool:
      vmImage: "ubuntu-16.04"
    strategy:
      matrix:
        base:
          config: base
        desktop:
          config: desktop
      maxParallel: 2
    steps:
      - bash: |
          set -ex
          sudo bash ubuntu.$(config).sh -d bionic -l us -u $(whoami)
          bash ubuntu.$(config).test.sh
