jobs:
  - job: ubuntu
    pool:
      vmImage: "ubuntu-16.04"
    strategy:
      matrix:
        base:
          config: base
        desktop:
          config: desktop
      maxParallel: 2
    container: ubuntu:bionic
    steps:
      - script: bash ubuntu.$(config).sh -d bionic -l us -u $(whoami)
      - script: bash ubuntu.$(config).test.sh
